-- MySQL Script generated by MySQL Workbench
-- vie 20 ago 2021 20:43:35 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database` ;

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`user` ;

CREATE TABLE IF NOT EXISTS `database`.`user` (
  `id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(64) NULL,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`auth` ;

CREATE TABLE IF NOT EXISTS `database`.`auth` (
  `id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(64) NULL,
  `password` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`shop` ;

CREATE TABLE IF NOT EXISTS `database`.`shop` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(64) NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shop_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_shop_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
