-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database` ;

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`auth` ;

CREATE TABLE IF NOT EXISTS `database`.`auth` (
  `id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(32) NULL,
  `password` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`address` ;

CREATE TABLE IF NOT EXISTS `database`.`address` (
  `id` VARCHAR(32) NOT NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`user` ;

CREATE TABLE IF NOT EXISTS `database`.`user` (
  `id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(32) NULL,
  `first_name` VARCHAR(64) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `profile_picture` VARCHAR(45) NULL,
  `auth_id` VARCHAR(32) NOT NULL,
  `address_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `auth_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_auth1_idx` (`auth_id` ASC),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_auth1`
    FOREIGN KEY (`auth_id`)
    REFERENCES `database`.`auth` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `database`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`shop` ;

CREATE TABLE IF NOT EXISTS `database`.`shop` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(64) NULL,
  `description` VARCHAR(45) NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `category` INT NOT NULL,
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shop_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_shop_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`product` ;

CREATE TABLE IF NOT EXISTS `database`.`product` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(64) NULL,
  `price` DECIMAL NULL,
  `description` TEXT NULL,
  `primary_image` VARCHAR(45) NULL,
  `shop_id` VARCHAR(32) NOT NULL,
  `category` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_product_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `database`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`order` ;

CREATE TABLE IF NOT EXISTS `database`.`order` (
  `id` VARCHAR(32) NOT NULL,
  `amount` VARCHAR(45) NULL,
  `date` TIMESTAMP NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`category` ;

CREATE TABLE IF NOT EXISTS `database`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`order_product` ;

CREATE TABLE IF NOT EXISTS `database`.`order_product` (
  `order_id` VARCHAR(32) NOT NULL,
  `product_id` VARCHAR(32) NOT NULL,
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `database`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `database`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`shop_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`shop_category` ;

CREATE TABLE IF NOT EXISTS `database`.`shop_category` (
  `shop_id` VARCHAR(32) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `category_id`),
  INDEX `fk_shop_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_shop_has_category_shop1_idx` (`shop_id` ASC),
  CONSTRAINT `fk_shop_has_category_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `database`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `database`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`product_category` ;

CREATE TABLE IF NOT EXISTS `database`.`product_category` (
  `product_id` VARCHAR(32) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_product_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_has_category_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `database`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `database`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
